Models/Admin.cs
namespace PakoLibrary.Models
{
    public class Admin
    {
        public int ID { get; set; }
        public required string Name { get; set; }
        public required string Password { get; set; }
    }
}

Models/Document.cs
using System.ComponentModel.DataAnnotations;

namespace PakoLibrary.Models
{
    public class Document
    {
        public int ID { get; set; }
        public required string Name { get; set; }
        public string? ShortDescription { get; set; }
        public required string PicturePath { get; set; }
        public required string PDF_Link { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace PakoLibrary.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PakoLibraryDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace PakoLibrary.Models
{
   public class PakoLibraryDbContext : DbContext
    {
        public PakoLibraryDbContext(DbContextOptions<PakoLibraryDbContext> options)
    : base(options){}

        public DbSet<Document> Document { get; set; }
        public DbSet<Admin> Admin { get; set; }

    }
}

Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using PakoLibrary.Filter;
using PakoLibrary.Models;

namespace PakoLibrary.Controllers
{
    public class AdminController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly PakoLibraryDbContext _dbContext;

        public AdminController(ILogger<HomeController> logger,
            PakoLibraryDbContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login(string Name, string Password)
        {
            var admin = _dbContext.Admin.FirstOrDefault(a => a.Name == Name
            && a.Password == Password);

            if (admin == null)
            {
                return RedirectToAction(nameof(Index));
            }

            HttpContext.Session.SetInt32("id", admin.ID);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        [UserFilter]
        public IActionResult Docs()
        {
            List<Document> documents = _dbContext.Document.ToList();
            return View(documents);
        }


    }
}

Controllers/DocumentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using PakoLibrary.Filter;
using PakoLibrary.Models;
using System.Linq.Expressions;

namespace PakoLibrary.Controllers
{
    [UserFilter]
    public class DocumentController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly PakoLibraryDbContext _dbContext;

        public DocumentController(ILogger<HomeController> logger,
            PakoLibraryDbContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save([FromForm] Document model)
        {
            try
            {
                if (model != null)
                {
                    var wwwRootPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
                    // Resim dosyası
                    var pictureFile = Request.Form.Files.FirstOrDefault(f => f.Name == "PicturePath");
                    string picturePath = null;

                    if (pictureFile != null && pictureFile.Length > 0)
                    {
                        var pictureSavePath = Path.Combine(wwwRootPath, "img");
                        var pictureFileName = $"{DateTime.Now:MMddHHmmss}.{pictureFile.FileName.Split(".").Last()}";  // Benzersiz dosya adı
                        var pictureFileUrl = Path.Combine(pictureSavePath, pictureFileName);

                        // Dosyayı kaydet
                        using (var fileStream = new FileStream(pictureFileUrl, FileMode.Create))
                        {
                            await pictureFile.CopyToAsync(fileStream);
                        }

                        picturePath = $"/img/{pictureFileName}";  // Web yolu
                    }

                    // PDF dosyası
                    var pdfFile = Request.Form.Files.FirstOrDefault(f => f.Name == "PDF_Link");
                    string pdfPath = null;

                    if (pdfFile != null && pdfFile.Length > 0)
                    {
                        var pdfSavePath = Path.Combine(wwwRootPath, "pdf");
                        var pdfFileName = $"{DateTime.Now:MMddHHmmss}.{pdfFile.FileName.Split(".").Last()}";  // Benzersiz dosya adı
                        var pdfFileUrl = Path.Combine(pdfSavePath, pdfFileName);

                        // Dosyayı kaydet
                        using (var fileStream = new FileStream(pdfFileUrl, FileMode.Create))
                        {
                            await pdfFile.CopyToAsync(fileStream);
                        }

                        pdfPath = $"/pdf/{pdfFileName}";  // Web yolu
                    }

                    // Yolu modelin alanlarına ekle
                    model.PicturePath = picturePath;
                    model.PDF_Link = pdfPath;


                    // Veritabanına kaydet
                    await _dbContext.AddAsync(model);
                    await _dbContext.SaveChangesAsync();

                    return Json(true);  // Başarı mesajı
                }
            }
            catch(Exception ex)
            {
                _logger.LogError($"Error: {ex.Message}, StackTrace: {ex.StackTrace}");
                return Json(new { success = false, message = ex.Message });
            }
            return Json(false);


        }


        public IActionResult DeleteDoc(int? id)
        {
            _dbContext.Remove(_dbContext.Document.FirstOrDefault(d => d.ID == id));
            _dbContext.SaveChanges();

            return RedirectToAction("Docs", "Admin");
        }

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using PakoLibrary.Models;

namespace PakoLibrary.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly PakoLibraryDbContext _dbContext;

        public HomeController(ILogger<HomeController> logger, 
            PakoLibraryDbContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public IActionResult Index(string query)
        {
            List<Document> documents = _dbContext.Document.ToList();

            if (!query.IsNullOrEmpty())
            {
                documents = _dbContext.Document.Where(d => d.Name.Contains(query)
                || d.ShortDescription.Contains(query)).ToList();
            }

            return View(documents);
        }
        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Admin/Docs.cshtml
@model IEnumerable<PakoLibrary.Models.Document>
<div class="container px-4 px-lg-5 mt-5">
        <button class="btn btn-outline-success" type="submit">
       <a asp-controller="Document" asp-action="Index" 
       style="text-decoration: none; color: inherit;">Add Doc</a>
   </button>
<table class="table table-hover">
    <thead>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">ShortDescription</th>
        <th scope="col">Picture</th>
        <th scope="col">PDF</th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
                        <tr>
                            <th scope="row">@item.ID</th>
                            <td>@item.Name</td>
                            <td>@item.ShortDescription</td>
                            <td>@item.PicturePath</td>
                            <td>@item.PDF_Link</td>
                            <td>
                                <a class="btn btn-danger" asp-route-id="@item.ID" asp-controller="Document" asp-action="DeleteDoc">sil</a>
                            </td>
                        </tr>
        }
    </tbody>
</table>
</div>

Views/Admin/Index.cshtml
<div class="container px-4 px-lg-5 mt-5">
        <h1>Login is for only admin stuff!</h1>
        <br />
<form method="POST" action="/Admin/Login">
    <div class="form-group">
        <input type="text" class="form-control" name="Name" placeholder="Name..."/>
    </div>
    <br />
    <div class="form-group">
        <input type="password" class="form-control" name="Password" placeholder="Password..."/>
    </div>
    <br />
    <button type="submit" class="btn btn-secondary">Login</button>
</form>
</div>

Views/Document/Index.cshtml
<div class="container px-4 px-lg-5 mt-5">
    <form method="POST" id="form" enctype="multipart/form-data">
        <div class="form-group">
            <input type="text" class="form-control" name="Name" id="title" placeholder="Name...">
        </div>
        <br/>
        <div class="form-group">
            <input type="text" class="form-control" name="ShortDescription" id="shortdesc" placeholder="Short description...">
        </div>
        <br/>
        <label>Picture</label>
        <div class="form-group">
            <input type="file" class="form-control" name="PicturePath">
        </div>
        <br/>
        <label>Doc</label>
        <div class="form-group">
            <input type="file" class="form-control" name="PDF_Link">
        </div>
        <br/>
        <div class="btn-group-toggle">
            <button type="button" onclick="Save()" class="btn btn-primary">Kaydet</button>
        </div>
    </form>
</div>

@section Scripts {
        <script>
            function Save() {
                var form = document.getElementById("form");
                var formData = new FormData(form);
   
                var data = Object.fromEntries(formData);

                console.log(data);

                var url = '/Document/Save';

    fetch(url, {
        method: 'POST',
        body: formData
    })
    .then(res => {
        if (!res.ok) {  
            throw new Error('Network response was not ok');
        }
        return res.json();  
    })
    .then(result => {
        alert("Document posted!");
    })
    .catch(error => {
        console.error("Error:", error);  
    });

            }
        </script>
}

Views/Home/Contact.cshtml
<div class="container px-4 px-lg-5 mt-5">
	<h1>CONTACT UmtiPako</h1>
	<br />
	<h4><a href="mailto:umutpaklaci@hotmail.com">umutpaklaci@hotmail.com</a></h4>
</div>

Views/Home/Index.cshtml
@model IEnumerable<PakoLibrary.Models.Document>

@{
	ViewData["Title"] = "Home Page";
    int? id = Context.Session.GetInt32("id");
}
<header class="bg-dark py-5">
	<div class="container px-4 px-lg-5 my-5">
		<div class="text-center text-white">
				<h1 class="display-4 fw-bolder">PakoLibrary</h1>
					<p class="lead fw-normal text-white-50 mb-0">umtipako's DOCs and stuff</p>
				</div>
			</div>
</header>
       <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-2">
            <div>
            <form class="d-flex" asp-action="Index" asp-controller="Home">
                <input name="query" style="box-shadow: 4px 4px 20px;" class="form-control me-1" type="search" placeholder="Search by name, doc type, author, composer, etc..." aria-label="Search" value="@ViewData["CurrentFilter"]">
                <button class="btn btn-dark" style="box-shadow: 4px 4px 20px;" type="submit"><i class="bi bi-search"></i></button>
            </form>
            </div>
            <br /><br />
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    @if (Model.Count() < 1){
                        <h5>Couldn't find anything.</h5>
                    }
                    else{
                @foreach (var item in Model)
                {
                                    <div class="col mb-5">
                                    <div class="card h-100" style="box-shadow: 10px 10px 20px;">
                                    <!-- PDF image-->
                                    <img class="card-img-top" src="@item.PicturePath" alt="..."  />
                                    <!-- PDF Details-->
                                    <div class="card-body p-4">
                                        <div class="text-center">
                                            <!-- Product name-->
                                            <h5 class="fw-bolder">@item.Name</h5>
                                            <!-- Product price-->
                                    @item.ShortDescription
                                        </div>
                                    </div>
                                    <!-- Product actions-->
                                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" 
                                            href="@item.PDF_Link" download>Download</a></div>
                                    </div>
                                   </div>                           
                                   </div>
                    }
 
                                                        
                    }
                   

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@{
    int? id = Context.Session.GetInt32("id");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PakoLibrary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/PakoLibrary.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">PakoLibrary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page"asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav-item"><a class="nav-link active" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                    <form class="d-flex">
                        @if (!id.HasValue){
                        <button class="btn btn-outline-dark" type="submit">
                                    <a asp-controller="Admin" asp-action="Index" style="text-decoration: none; color: inherit;"
                                >Login</a>
                        </button>
                        } 
                        else{
                            <button class="btn btn-outline-dark me-2" type="submit">
                                        <a asp-controller="Admin" asp-action="Logout" style="text-decoration: none; color: inherit;"
                                    >Logout</a>
                            </button>
                                <button class="btn btn-outline-dark" type="submit">
                                            <a asp-controller="Admin" asp-action="Docs" style="text-decoration: none; color: inherit;"
                                        >Docs</a>
                             </button>
                        }
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class=".container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PakoLibrary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>